황수경 6일차 문제 풀이
SolveEveryday/SolveEveryday pull request #16
Opened 2022-10-08 04:16 UTC by sukyeongh

## 로직

1. 단어 하나를 반복
1-2. 같은 문자가 반복되는 경우를 지운 단어를 새로 만듦
2.  1-2에서 만든 새로운 단어로 문자를 반복
2-1. Set으로 이미 존재했던 단어 일 경우 그룹 단어가 아니므로 count를 하나 증가
3. 전체 갯수에서 아닐 경우의 갯수 뺌(N-notGroupWord 갯수)

## 복잡도

시간복잡도 O(N^2)
공간복잡도 O(N)

## 채점 결과

<img width="1141" alt="image" src="https://user-images.githubusercontent.com/50071076/194687642-a28c5e76-3af6-40a2-91ab-4514ea5045f1.png">

2022-10-08 12:05 UTC, deepredk requested changes
로직 설명이 잘 이해안되는데
단어나 문자를 '반복한다'는게 뭘 말하는거에요??

반복한다 = 문자열이 ab라면 abab로 만든다 인줄 알았는데
그렇게 해석하자니까 2-1에서 Set으로 abab가 이미 존재했던 단어인걸 체크할 이유가 없을 것 같네요


아 그리고 복잡도에서 N은 혹시 어떤걸 기준으로 잡은거에요?

2022-10-09 11:29 UTC, sukyeongh commented
반복된다 말보다 순회가 맞는 말 같습네댱 수정했습니다!

N은 set객체를 사용한 변수 기준으로 적었습니다.

2022-10-09 12:39 UTC, deepredk approved these changes
빅오표기법에서 사용하는 N은 그냥 표현할때 끌어다쓰는 실체없는 무엇이 아닙니다. 대부분의 알고리즘에서는 입력의 크기가 명확해서 N이 무엇을 말하는지 자주 설명이 생략되곤 하는데 항상 명확한 기준 변수(아이템의 개수, 정수의 크기, 문자열의 크기, 정수의 자리수)가 있고 그걸 N으로 둔겁니다
```java
for(int i=0; i<n; i++) {
    for(int j=0; j<m; j++) {
        System.out.println(n * m);
    }
}
```
예를 들자면 위 알고리즘의 시간 복잡도는 O(NM)입니다

알고리즘의 실행횟수가 구체적으로 무엇에 비례해서 증가하는지 생각해보시면 좋을 것 같습니다

2022-10-09 12:46 UTC, deepredk commented
저는 문자열의 길이를 기준 N으로 잡았고, 그렇게 기준점을 잡았을 때 시간복잡도가 O(N)이라고 생각됐습니다

2022-10-09 14:11 UTC, sukyeongh commented
궁금한 부분이 그러면 만약 진홍씨가 문자 하나를 기준으로 잡는다고 하면 시간복잡도는 O(N^2)가 되는 건가요?

2022-10-09 14:13 UTC, deepredk commented
?? O(N)이요!

2022-10-09 14:13 UTC, deepredk commented
슬랙 DM할게요

2022-10-09 14:28 UTC, sukyeongh commented
덕분에 이해됐습니당! 감사합니다 수정했습네댜

2022-10-09 14:55 UTC, sue4869 approved these changes
👍

2022-10-09 16:26 UTC, merged