유수민 10일차 문제 풀이
SolveEveryday/SolveEveryday pull request #29
Opened 2022-10-12 14:26 UTC by sue4869

## 로직
1. 입력받은 알파벳의 사용 개수를 센다
2. 실패할 경우에 해당하는지 판단한다. 
- 전체 길이가 홀수일때 알파벳의 사용 개수가 홀수인 것이 무조건 1개여야 한다. 홀수인 알파벳의 사용개수가 나타났을 경우, 해당 알파벳은 중간 단어에 해당한다. 
- 전체 길이가 짝수일때 알파벳의 사용 개수가 홀수가 있으면 안된다. 
3. 반복구간의 앞부분을 구성하고 중간단어를 붙인다. 
4. 반복구간을 뒤집어 뒷부분으로 구성하여 이어 붙인다. 

## 복잡도

시간복잡도 O(N²)
공간복잡도 O(1)

## 채점 결과

![image](https://user-images.githubusercontent.com/68679529/195369848-bd0ea995-9998-4625-8a96-6e8a3a78d3cd.png)

2022-10-13 00:04 UTC, HanHyunsoo approved these changes
고생하셨습니다!!!

2022-10-13 00:13 UTC, deepredk requested changes
시간복잡도가 왜 N^2인가요??

for문 2번 중첩된 거 때문에 그렇게 생각하신거 아닐까 싶은데
```
for (int i = 0; i < 100; i++) {
   for (int j = 0; j < 100; j++) {
       for (int j = 0; j < 100; j++) {

        }
   }
}
```
위는 시간복잡도가 O(1)입니다!
시간복잡도 쪽 한번 다시 짚어보시면 좋을 것 같습니다

2022-10-15 11:55 UTC, sue4869 commented
시간 복잡도 O(N)으로 수정하였습니다. @deepredk 
for (int x = 0; x < len; x++) {
        alphabat[input[x] - 'A']++;
    }
위 코드를 기준으로 하였습니다.

2022-10-15 12:07 UTC, deepredk commented
@sue4869 
왜 전체 코드가 아닌 일부 코드 기준으로 산정하신건가요??

2022-10-15 12:11 UTC, sue4869 commented
@deepredk 
전체 코드를 다 고려하였는데 위에 예시된 코드 이외의 다른 코드는 O(1)에 해당하여 시간복잡도 계산에 영향을 주지 않는다고 생각했습니다.

2022-10-15 12:13 UTC, deepredk commented
아아 이해했습니다

2022-10-15 12:14 UTC, deepredk commented on Study01 - Implementation/Day10/ysm.cpp
> +                    sen += 'A' + y;
요 50줄이 (N/2)번 실행될거라 이 부분도 O(N)에 해당하긴 합니다

2022-10-15 12:14 UTC, deepredk approved these changes
고생하셨습니다!

2022-10-15 12:15 UTC, sue4869 commented on Study01 - Implementation/Day10/ysm.cpp
> +                    sen += 'A' + y;
오호 정말 그렇네요! 찾아주셔서 감사합니다

2022-10-15 12:16 UTC, merged