한현수 14일차 문제 풀이
SolveEveryday/SolveEveryday pull request #40
Opened 2022-10-16 10:36 UTC by HanHyunsoo

## 로직

1. 국가번호, 금, 은, 동의 정보를 각각 입력받아 리스트에 저장한다.
2. 금, 은, 동의 조건으로 정렬을 한다.
3. 인접한 나라끼리 비교하여 순위를 매긴다.

## 복잡도

시간복잡도 O(n)
공간복잡도 O(n)

n은 입력받은 나라의 수

## 채점 결과

<img width="916" alt="스크린샷 2022-10-16 오후 7 35 38" src="https://user-images.githubusercontent.com/37373826/196030651-5f409860-6624-4839-bf78-3a359f48c684.png">

2022-10-16 10:38 UTC, deepredk requested changes
Collctions.sort()가 O(NlogN) 시간복잡도로 구현돼있어 O(N)보다는 O(NlogN)이 적합한 복잡도 표현일 것 같습니다!

2022-10-16 10:40 UTC, HanHyunsoo commented
@deepredk 
정렬과는 별개로 순위를 매기는 과정에서 다시한번 리스트를 처음부터 끝까지 돌아서 N까지라고 생각했어요

2022-10-16 10:41 UTC, HanHyunsoo commented
@deepredk 
제가 잘못이해했네요 감사합니다!

2022-10-16 10:42 UTC, deepredk approved these changes
👍👍
라이브러리 함수 시간복잡도도 종종 고려할 필요가 있더라고요

2022-10-16 10:55 UTC, sue4869 commented
readme 빼먹으셨어용~

2022-10-16 10:58 UTC, HanHyunsoo commented
@sue4869 추가 했습니다 감사합니다!

2022-10-17 04:58 UTC, sue4869 approved these changes
👍

2022-10-17 08:31 UTC, merged