solve : 19일차 문제 풀이
SolveEveryday/SolveEveryday pull request #56
Opened 2022-10-21 16:21 UTC by HanHyunsoo

## 로직

1. R, C 연산을 판단하여 맞는 연산을 수행한다.
    * 이 과정에서 얻은 연산을 조건에 맞게 정렬하여 다시 matrix에 넣는다.
2. 횟수가 백번이 넘으면 -1 아니라면 그 수를 출력한다.

정렬 메서드는 시간이 부족해서 내부 정렬 메서드를 사용했습니다.

## 복잡도
N 은 row * col

시간복잡도 - O(N log N)
공간복잡도 - O(N)

## 채점 결과

<img width="929" alt="스크린샷 2022-10-22 오전 1 19 54" src="https://user-images.githubusercontent.com/37373826/197242714-5b2fb731-132a-4996-a9ac-f1e37bbb52a4.png">

2022-10-21 21:22 UTC, deepredk requested changes
직접 구현한 정렬 사용합시다용
스터디 내에서 한번 타협하면 계속 타협하게 되더라구요ㅠㅋ

새벽까지 고생하셨어요!

2022-10-21 21:27 UTC, HanHyunsoo commented
@deepredk 넵 죄송합니다 시간이 없다보니 그런거같아요ㅠ
정렬 메서드 구현해서 다시 커밋할게요!!

2022-10-21 21:28 UTC, deepredk commented
괜찮아요괜찮아요 ㅎㅎ 이해합니다
네넵!

2022-10-22 13:17 UTC, sue4869 approved these changes
👍

2022-10-23 14:22 UTC, deepredk approved these changes

2022-10-23 14:22 UTC, merged